apiVersion: v1
kind: Service
metadata: 
  name: servico-demo
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
  selector:
    name: aplicacao-demo-pod

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aplicacao-demo
spec:
  selector:
    matchLabels:
      name: aplicacao-demo-pod
  template:
    metadata:
      labels:
        name: aplicacao-demo-pod
    spec:
      containers:
        - name: container-aplicacao
          image: igoragueme/efk-demo:1.5
          resources:
            requests:
              cpu: 100m
          ports:
            - containerPort: 80    
